data:
  precs: ['576', '672', '768', '864', '960']
  lim_around_wt: [2, 4, 2, 2]
  shape: [44, 44]
  z: 90
  regions: [6, 3] # Simulation regions per direction
  figures:
    plot_wf_slices: True
    # For visualizing original chaman simulations slices
    clim_ux: [0, 12]
    clim_uy: [-4, 4]
    lw: 0.3

train:
  device: 'cuda:1'
  learning_rate: 1.0e-2
  num_epochs: 50
  batch_size: 64
  num_workers: 4 # number of processes that gen batches in parallel