ops:
  neptune_logger: True

data:
  wt_grid: [3, 5]
  precs: ['576', '672', '768', '864', '960']
  turns: ['n7', 'n5', 'n2', 'pr', 'p2', 'p5', 'p7']
  t_window: 1000
  lim_around_wt: [2, 4, 2, 2]
  wt_diam: 126
  z: 90
  regions: [6, 3] # Simulation regions per direction
  fields: ['UMean']
  figures:
    plot_wf_slices: False
    # For visualizing original chaman simulations slices
    clim_ux: [0, 12]
    clim_uy: [-4, 4]
    lw: 0.3
  size: [64, 64]
  channels: 1
  normalization:
    type: 'min_max' # 'min_max' or 'z_score'
    mean_std: [null, null] # if null: mean, std of dataset
    range: [-1, 1]
  sampling_strategy: 'interp' # 'crop' or 'interp'

models:
  f_g: 64
  f_d: 64
  load: False
  save: True
  save_every: 1000
  name_gen: 'wake_gan_gen.pth'
  name_disc: 'wake_gan_disc.pth'

train:
  device: 'cuda:1'
  lr: 1.0e-3
  num_epochs: 60
  f_mse: 0.5
  batch_size: 32
  multibatch: True
  num_workers: 8 # number of processes that gen batches in parallel

validation:
  kfold: False # If false train with all training data
  n_splits: 5 # For k-fold cross validation