data:
  precs: ['576', '672', '768', '864', '960']
  lim_around_wt: [2, 4, 2, 2]
  wt_diam: 126
  shape: [44, 44]
  z: 90
  regions: [6, 3] # Simulation regions per direction
  fields: ['UMean']
  figures:
    plot_wf_slices: False
    # For visualizing original chaman simulations slices
    clim_ux: [0, 12]
    clim_uy: [-4, 4]
    lw: 0.3
  final_size: [64, 64]
  channels: 1

models:
  f_g: 64
  f_d: 64
  load: False
  save: False
  name_gen: 'wake_gan_gen.pth'
  name_disc: 'wake_gan_disc.pth'

train:
  device: 'cuda:1'
  lr: 1.0e-4
  num_epochs: 100
  batch_size: 32
  multibatch: True
  num_workers: 8 # number of processes that gen batches in parallel

validation:
  kfold: False # If false train with all training data
  n_splits: 5 # For k-fold cross validation